# Generated by Django 5.1.15 on 2026-07-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uprice',
            new_name='price',
        ),
    ]
